/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.shelf.scheduler;

import io.shelf.client.HashRing;

import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/**
 * Helper bridging the {@link HashRing} HRW selector to Trino's
 * {@code ConnectorSplit#getAffinityKey()} SPI shape.
 *
 * <p>Background — Trino PR
 * <a href="https://github.com/trinodb/trino/pull/29182">#29182</a> ("Route splits
 * by affinity key in the scheduler", merged 2026-04-27) adds a
 * {@code getAffinityKey()} hook to {@code ConnectorSplit}. The engine
 * consistent-hashes the returned key over the live worker set, so all splits
 * sharing a key are routed to the same Trino worker. That worker then keeps a
 * warm Shelf TCP pool to whichever Shelf pod owns the underlying cache key,
 * which in turn:
 *
 * <ul>
 *   <li>halves cross-AZ data egress whenever the worker and the Shelf pod
 *       happen to land in the same AZ;</li>
 *   <li>collapses the cold-fetch storm during KEDA scale-out (newly-admitted
 *       Trino workers don't all hammer Shelf at once for the same etag);</li>
 *   <li>tightens the L1/page-cache locality on the worker JVM since the
 *       Iceberg metadata cache (Trino {@code iceberg.metadata-cache.enabled})
 *       only delivers full benefit when the same files map to the same
 *       worker.</li>
 * </ul>
 *
 * <p>Shelf is a filesystem-swap (ADR-0012), not a Trino connector fork, so the
 * Shelf-side deliverable is just this helper. The actual scheduler activation
 * lands as a small patch in <em>Trino's</em> Iceberg connector that calls
 * {@link #forKey(byte[], List)} from {@code IcebergSplit#getAffinityKey()}.
 * See {@code docs/integrations/trino-iceberg-affinity-key.md} for the patch
 * sketch.
 *
 * <h2>Hash function</h2>
 *
 * Identical to {@code shelfd::router::hrw_score} (see
 * {@code shelfd/src/router.rs}): SHA-256 over {@code key || podId.utf8()},
 * top-53 bits of the BE u64 prefix mapped to a [0, 1) double, score is
 * {@code weight / -ln(x)}, ties broken by lexicographically-smaller pod id.
 * Cross-language parity is asserted by
 * {@code io.shelf.client.HashRingTest#ownerMatchesGoldenFixture} against
 * {@code shelfd/tests/fixtures/hrw_golden_vectors.txt}; the fixture is
 * generated by the Rust side ({@code SHELF_REGEN_FIXTURES=1 cargo test -p
 * shelfd --lib router::tests}). This helper does not introduce a second hash
 * function — it delegates to {@link HashRing} verbatim — so the parity
 * guarantee carries over by construction.
 *
 * <h2>Why this lives in {@code io.shelf.scheduler}, not {@code io.shelf.client}</h2>
 *
 * {@link HashRing} models the membership-aware ring used by the
 * {@code ShelfHttpClient} runtime to decide which pod a body fetch should
 * target. {@link ShelfAffinityKey} models the engine-side scheduler decision —
 * it has no notion of weight, takes a flat pod-id list, and returns the owner
 * id as a {@link String}. Splitting the two keeps the runtime client free of
 * Trino-scheduler-specific assumptions.
 *
 * <h2>Failure modes (fail-open)</h2>
 *
 * Per ADR-0012, every Shelf-side hook in the Trino plugin is fail-open: if
 * the helper cannot pick an owner ({@code podIds} is empty, or {@code key} is
 * {@code null}), we return {@link Optional#empty()}. The Trino fork's
 * {@code IcebergSplit#getAffinityKey()} should map an empty result to
 * {@code Optional.empty()} so Trino falls through to its default scheduler
 * (usually {@link io.trino.spi.HostAddress}-based hint scheduling). That
 * preserves correctness even if the Shelf membership snapshot the engine sees
 * is stale or the connector forgot to plumb pod ids.
 */
public final class ShelfAffinityKey
{
    private ShelfAffinityKey() {}

    /**
     * Resolve the Shelf pod that owns {@code key} and return its id.
     *
     * <p>This is the canonical entry point for Trino-side scheduler patches.
     * The returned {@link String} is the pod id (e.g. {@code shelf-2}); the
     * Trino fork should wrap it in {@code Optional.of(...)} as the
     * {@code ConnectorSplit#getAffinityKey()} return value.
     *
     * @param key     the bytes the caller wants HRW-routed. Typical choices,
     *                in order of preference:
     *                <ol>
     *                  <li>The full SHELF-04 cache key (32 bytes,
     *                      {@code sha256(etag || u64_le(offset) ||
     *                      u64_le(length) || u32_le(rg_ordinal))}). Most
     *                      precise: every row group routes to its actual
     *                      Shelf owner.</li>
     *                  <li>The S3 object's ETag bytes (typically MD5 or
     *                      multipart MD5-of-MD5s). Coarser; all row groups in
     *                      a file share an owner.</li>
     *                  <li>The S3 path bytes. Coarsest; tolerates ETag
     *                      mutations across snapshots but loses precision on
     *                      multi-snapshot tables.</li>
     *                </ol>
     * @param podIds  current Shelf pod-id list, usually obtained from the
     *                membership resolver's last refresh
     *                ({@code MembershipResolver#snapshot} or equivalent).
     *                Order does not matter; ties are broken by
     *                lexicographically-smaller pod id.
     * @return the owning pod id, or {@link Optional#empty()} if {@code podIds}
     *         is empty or {@code null}.
     * @throws NullPointerException if {@code key} is {@code null}.
     */
    public static Optional<String> forKey(byte[] key, List<String> podIds)
    {
        Objects.requireNonNull(key, "key");
        if (podIds == null || podIds.isEmpty()) {
            return Optional.empty();
        }
        List<HashRing.Node> nodes = new ArrayList<>(podIds.size());
        for (String id : podIds) {
            Objects.requireNonNull(id, "podId entries must be non-null");
            nodes.add(new HashRing.Node(id, 1.0));
        }
        return new HashRing(nodes).ownerFor(key).map(HashRing.Node::podId);
    }

    /**
     * Convenience overload that UTF-8 encodes a {@link String} key before
     * delegating to {@link #forKey(byte[], List)}.
     *
     * <p>Use this when the Trino fork has only a string identifier handy
     * (e.g. the file path, or a precomputed lowercase-hex of the SHELF-04
     * key). For raw cache-key bytes, prefer the {@code byte[]} overload —
     * encoding 32 bytes as hex and re-encoding as UTF-8 doubles the SHA-256
     * input for no additional locality benefit.
     *
     * @param key     UTF-8 string interpretation of the routing key.
     * @param podIds  current Shelf pod-id list.
     * @return the owning pod id, or {@link Optional#empty()} on empty
     *         {@code podIds}.
     * @throws NullPointerException if {@code key} is {@code null}.
     */
    public static Optional<String> forKey(String key, List<String> podIds)
    {
        Objects.requireNonNull(key, "key");
        return forKey(key.getBytes(StandardCharsets.UTF_8), podIds);
    }
}
