#!/usr/bin/env python3
"""H2 — dbt-emit: convert shelf-advisor recommendations into dbt model PRs.

Reads the JSON emitted by :mod:`shelf_advisor`, produces one dbt
model file per recommendation under
``models/shelf_materialized/`` in the target repo, and opens a
single pull request that bundles all new models.

The tool is deliberately **model-YAML-first**, not SQL-first:
MetricFlow / dbt-trino already know how to materialise
``materialized='materialized_view'`` against Iceberg. We only
need to emit a plain ``SELECT`` block — the canonicalised plan
from the advisor carries the grain, the group-by columns, and
the referenced tables, so the emitter is mostly book-keeping.

Governance hook: human review on the PR is the approval
surface. No model auto-merges.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import logging
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile
import textwrap
from typing import Iterable

logger = logging.getLogger("shelf-dbt-emit")


# ---------------------------------------------------------------------------
# Model rendering
# ---------------------------------------------------------------------------

MODEL_DIR = "models/shelf_materialized"


def _slug(fingerprint: str) -> str:
    """Stable short name per fingerprint: first 10 hex chars."""
    return "shelf_mv_" + fingerprint[:10]


def _model_sql(rec: dict) -> str:
    """Render a dbt model file for one recommendation.

    The SQL body is elided — the advisor's canonical plan
    captures intent but isn't guaranteed to be syntactically
    valid SQL. Reviewers fill in the ``SELECT`` body before
    merging; the template spells that out explicitly so the PR
    cannot accidentally ship a half-finished query.
    """
    name = _slug(rec["fingerprint"])
    tables = "\n".join(f"--   - {t}" for t in rec.get("tables", []))
    net = rec.get("net_benefit_per_day_bytes", 0) / (1024 ** 4)
    return textwrap.dedent(
        f"""\
        -- shelf-advisor recommendation · {rec['fingerprint']}
        -- runs/day:        {rec['runs_per_day']:.1f}
        -- bytes saved/day: {rec['bytes_saved_per_day']:.2e}
        -- net benefit/day: {net:.3f} TiB
        -- covers queries against:
        {tables}
        --
        -- REVIEWER NOTE: complete the SELECT body against the
        -- canonicalised plan below. The advisor deliberately
        -- does NOT auto-generate SQL — a human lands the query
        -- so semantic drift between fingerprint and text is
        -- caught at review time.
        --
        -- canonical_plan:
        {_indent_comment(rec['canonical_plan'])}

        {{{{ config(
            materialized='materialized_view',
            file_format='iceberg'
        ) }}}}

        SELECT
            -- TODO(reviewer): project columns per canonical_plan
            NULL AS placeholder
        FROM {{{{ ref('dummy_source') }}}}
        WHERE FALSE -- model is inert until reviewer replaces
        """
    ) + "\n"


def _indent_comment(text: str) -> str:
    lines = text.splitlines() or [""]
    return "\n".join("--   " + line for line in lines)


def _model_schema_yaml(rec: dict) -> str:
    name = _slug(rec["fingerprint"])
    net = rec.get("net_benefit_per_day_bytes", 0) / (1024 ** 4)
    return textwrap.dedent(
        f"""\
        version: 2

        models:
          - name: {name}
            description: |
              Shelf-advisor MV candidate (fingerprint {rec['fingerprint']}).
              Runs/day: {rec['runs_per_day']:.1f}
              Net benefit/day: {net:.3f} TiB
            meta:
              shelf:
                fingerprint: {rec['fingerprint']}
                runs_per_day: {rec['runs_per_day']:.3f}
                bytes_saved_per_day: {rec['bytes_saved_per_day']:.0f}
                first_seen: {rec.get('first_seen')}
                last_seen: {rec.get('last_seen')}
        """
    )


# ---------------------------------------------------------------------------
# Git + GitHub wiring
# ---------------------------------------------------------------------------

def _run(cmd: list[str], *, cwd: pathlib.Path | None = None) -> None:
    logger.debug("$ %s", " ".join(cmd))
    subprocess.run(cmd, cwd=cwd, check=True)


def _render_pr_body(recs: list[dict]) -> str:
    lines = [
        "## Shelf-advisor MV recommendations",
        "",
        "This PR is generated by `tools/dbt_emit.py` from the nightly",
        "`shelf-advisor` run. It lands one `materialized_view` model per",
        "recommended fingerprint.",
        "",
        "### Shortlist",
        "",
        "| Fingerprint | Runs/day | Bytes saved/day | Net benefit/day |",
        "| --- | ---: | ---: | ---: |",
    ]
    for r in recs:
        net = r.get("net_benefit_per_day_bytes", 0) / (1024 ** 4)
        lines.append(
            f"| `{r['fingerprint'][:12]}` | {r['runs_per_day']:.1f} "
            f"| {r['bytes_saved_per_day']:.2e} B | {net:.3f} TiB |"
        )
    lines += [
        "",
        "### Reviewer checklist",
        "",
        "- [ ] Each model's `SELECT` body is filled in to match its",
        "      `canonical_plan` comment.",
        "- [ ] `dbt compile` passes.",
        "- [ ] The MV's base tables are on the Track-H allowlist",
        "      (`infra/shelf/mv-allowlist.yaml`).",
        "",
        "Auto-merge is **not** enabled on this PR.",
    ]
    return "\n".join(lines)


def emit(
    recs: list[dict],
    repo: pathlib.Path,
    *,
    branch: str | None = None,
    commit: bool = True,
    open_pr: bool = False,
) -> pathlib.Path:
    """Write models into ``repo`` and optionally create a PR.

    Returns the directory under ``repo`` where models were written.
    """
    if not recs:
        logger.info("no recommendations; nothing to emit")
        return repo / MODEL_DIR

    out_dir = repo / MODEL_DIR
    out_dir.mkdir(parents=True, exist_ok=True)

    for rec in recs:
        name = _slug(rec["fingerprint"])
        (out_dir / f"{name}.sql").write_text(_model_sql(rec))
        (out_dir / f"{name}.yml").write_text(_model_schema_yaml(rec))

    if not commit:
        return out_dir

    stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%d")
    branch = branch or f"shelf-advisor/mv-{stamp}"
    _run(["git", "checkout", "-B", branch], cwd=repo)
    _run(["git", "add", MODEL_DIR], cwd=repo)
    _run([
        "git", "commit", "-m",
        f"chore(shelf): MV recommendations for {stamp}",
    ], cwd=repo)

    if open_pr:
        body = _render_pr_body(recs)
        with tempfile.NamedTemporaryFile("w", suffix=".md", delete=False) as f:
            f.write(body)
            body_path = f.name
        _run([
            "gh", "pr", "create",
            "--title", f"shelf-advisor MV recommendations {stamp}",
            "--body-file", body_path,
            "--base", "main",
        ], cwd=repo)
    return out_dir


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--recommendations", required=True, type=pathlib.Path)
    parser.add_argument("--repo", required=True, type=pathlib.Path,
                        help="local clone of the target dbt repo (already on main)")
    parser.add_argument("--branch", help="override the auto-generated branch name")
    parser.add_argument("--no-commit", action="store_true",
                        help="write models but don't git-commit or open a PR")
    parser.add_argument("--open-pr", action="store_true",
                        help="open a GitHub PR via the gh CLI")
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.DEBUG if args.verbose else logging.INFO)

    payload = json.loads(args.recommendations.read_text())
    recs = payload.get("recommendations", [])
    logger.info("loaded %d recommendations", len(recs))

    emit(
        recs,
        args.repo,
        branch=args.branch,
        commit=not args.no_commit,
        open_pr=args.open_pr,
    )
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main(sys.argv[1:]))
